# Default values for wiremock.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

image:
  repository: armdockerhub.rnd.ericsson.se/wiremock/wiremock
  tag: 2.31.0
  pullPolicy: IfNotPresent

service:
  name: wiremock
  type: ClusterIP
  httpPort: 8080
  httpsPort: 8443

global:
  security:
    tls:
      enabled: false
