#
# COPYRIGHT Ericsson 2023
#
#
#
# The copyright to the computer program(s) herein is the property of
#
# Ericsson Inc. The programs may be used and/or copied only with written
#
# permission from Ericsson Inc. or in accordance with the terms and
#
# conditions stipulated in the agreement/contract under which the
#
# program(s) have been supplied.
#

# Avro Producer Configuration
# Default values for executing the tool locally with TLS enabled

dmm:
  schemaRegistry:
    url: https://localhost:8443
    tls:
      enabled: true
      trustStoreLocation: ${ROOT_WRITE_PATH:/tmp}/rootca/truststore.p12
      trustStorePassword: password
      trustStoreType: PKCS12
      keyStoreLocation: ${ROOT_WRITE_PATH:/tmp}/server/keystore.p12
      keyStorePassword: password
      keyStoreType: PKCS12
kafka:
  bootstrapServers: localhost:9093
  tls:
    enabled: true
    trustStoreLocation: ${ROOT_WRITE_PATH:/tmp}/rootca/truststore.p12
    trustStorePassword: password
    trustStoreType: PKCS12
    keyStoreLocation: ${ROOT_WRITE_PATH:/tmp}/kafka/keystore.p12
    keyStorePassword: password
    keyStoreType: PKCS12

data:
  period: 10
