#
# COPYRIGHT Ericsson 2023
#
#
#
# The copyright to the computer program(s) herein is the property of
#
# Ericsson Inc. The programs may be used and/or copied only with written
#
# permission from Ericsson Inc. or in accordance with the terms and
#
# conditions stipulated in the agreement/contract under which the
#
# program(s) have been supplied.
#

# Avro Producer Configuration
# Default values for executing the tool locally with TLS disabled

dmm:
  schemaRegistry:
    url: http://localhost:8080
kafka:
  bootstrapServers: localhost:9092

data:
  period: 10
