#
# COPYRIGHT Ericsson 2023
#
#
#
# The copyright to the computer program(s) herein is the property of
#
# Ericsson Inc. The programs may be used and/or copied only with written
#
# permission from Ericsson Inc. or in accordance with the terms and
#
# conditions stipulated in the agreement/contract under which the
#
# program(s) have been supplied.
#

# Avro Producer Configuration
# Default values for executing the tool in k8s cluster with TLS enabled

dmm:
  schemaRegistry:
    url: http://wiremock:8080
    # Enabling tls for this connection is not working when running this tool in the k8s cluster with SIP-TLS.
    # Given that we are using wiremock for our testing that supports http and https, then it is
    # acceptable to use a http connection here.
    # https://eteamproject.internal.ericsson.com/browse/ESOA-4969
    tls:
      enabled: false
      trustStoreLocation: /tmp/rootca/truststore.p12
      trustStorePassword: password
      trustStoreType: PKCS12
      keyStoreLocation: /tmp/server/keystore.p12
      keyStorePassword: password
      keyStoreType: PKCS12
kafka:
  bootstrapServers: eric-oss-dmm-kf-op-sz-kafka-bootstrap:9093
  tls:
    enabled: true
    trustStoreLocation: /tmp/rootca/truststore.p12
    trustStorePassword: password
    trustStoreType: PKCS12
    keyStoreLocation: /tmp/kafka/keystore.p12
    keyStorePassword: password
    keyStoreType: PKCS12