#
# COPYRIGHT Ericsson 2023
#
#
#
# The copyright to the computer program(s) herein is the property of
#
# Ericsson Inc. The programs may be used and/or copied only with written
#
# permission from Ericsson Inc. or in accordance with the terms and
#
# conditions stipulated in the agreement/contract under which the
#
# program(s) have been supplied.
#

{{- $g := fromJson (include "eric-oss-assurance-augmentation.global" .) -}}
{{- if $g.security.tls.enabled }}
apiVersion: siptls.sec.ericsson.com/v1
kind: InternalCertificate
metadata:
  name: {{ include "eric-oss-assurance-augmentation.fullname" . }}-log-cert
  labels:
  {{- include "eric-oss-assurance-augmentation.labels" . | nindent 4 }}
  annotations:
  {{- include "eric-oss-assurance-augmentation.annotations" . | nindent 4 }}
spec:
  kubernetes:
    generatedSecretName: {{ include "eric-oss-assurance-augmentation.fullname" . }}-log-cert
    secretType: tls
  certificate:
    extendedKeyUsage:
      tlsClientAuth: true
      tlsServerAuth: false
    subject:
      cn: {{ include "eric-oss-assurance-augmentation.fullname" . }}
    issuer:
      reference: eric-log-transformer-input-ca-cert
{{- end }}
