#
# COPYRIGHT Ericsson 2021
#
#
#
# The copyright to the computer program(s) herein is the property of
#
# Ericsson Inc. The programs may be used and/or copied only with written
#
# permission from Ericsson Inc. or in accordance with the terms and
#
# conditions stipulated in the agreement/contract under which the
#
# program(s) have been supplied.
#

apiVersion: v1
kind: Service
metadata:
  name: {{ include "eric-oss-assurance-augmentation.fullname" . }}
  labels:
  {{- include "eric-oss-assurance-augmentation.labels" . | nindent 4 }}
  annotations:
  {{- include "eric-oss-assurance-augmentation.annotations" . | nindent 4 }}
spec:
  type: {{ .Values.service.type | quote }}
  {{- if .Values.global }}
  {{- if .Values.global.internalIPFamily }}
  ipFamilies: [{{ .Values.global.internalIPFamily }}]
  {{- end }}
  {{- end }}
  ports:
    - port: {{ include "eric-oss-assurance-augmentation.service-port" . }}
    {{- $g := fromJson (include "eric-oss-assurance-augmentation.global" .) -}}
    {{- if $g.security.tls.enabled }}
      name: rest-api-tls
    {{- else }}
      name: rest-api
    {{- end }}
      protocol: TCP
  selector:
    app.kubernetes.io/name: {{ include "eric-oss-assurance-augmentation.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
